[package]
name = "nannou-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"

[[example]]
name = "hello-world"
path = "hello-world/hello-world.rs"

[[example]]
name = "mouse-event"
path = "mouse-event/mouse-event.rs"